### PR TITLE
Fix/featured image height

### PR DESCRIPTION
**Pull request by smit-patadiya**
Fixes image height issue with pure CSS way.
- Calculate padding based on image width & height ratio.

### CODE REVIEW

**Comment by luisherranz** [comment]
I know this is closed now, but I'd like to comment that you shouldn't use the React's `style` prop, but the Emtion's `css` prop: https://emotion.sh/docs/css-prop#string-styles

Instead of this:

```jsx
const calculatedImageRatio = media.media_details.height * 100 / media.media_details.width;
const imageStyle = { paddingTop: `${calculatedImageRatio}%`; };  

return (
    <Container>
    <Container style={ imageStyle }>
      <StyledImage
        alt={ media.title.rendered }
        src={ media.source_url }
```

Do this:
```jsx
const calculatedImageRatio = media.media_details.height * 100 / media.media_details.width;

return (
    <Container>
    <Container css={css`{ padding-top: ${calculatedImageRatio}%`}>
      <StyledImage
        alt={ media.title.rendered }
        src={ media.source_url }
```

If you use the `style` prop it ends up in an inline style. That means Emotion cannot optimize that CSS and it will break AMP (because inline styles in AMP are forbidden).

@SantosGuillamot maybe we can add a note about this in the CSS docs you are working on :)

**Comment by SantosGuillamot** [comment]
Yeah sure, I will add it in the CSS guide for sure :)

**Comment by smit-patadiya** [comment]
@luisherranz Thanks,
Added Emotion for the featured image.

**Comment by luisherranz** [comment]
Awesome! :)

I've pushed it to production: https://twentynineteen.frontity.org

**Comment by smit-patadiya** [comment]
I'm thinking to do more image optimization. Because the main image having greater file size. Instead of it, we can use  post thumbnail image (If not found then we will have a fall-back to the original image)

As most of the post has a post-thumbnail image. [Check this example](https://smitpatadiya.com/wp-content/uploads/2019/07/Screenshot-2019-07-31-at-8.50.22-PM.png)

Original Image:- [https://test.frontity.io/wp-content/uploads/2016/11/Iceland-test.jpg](https://test.frontity.io/wp-content/uploads/2016/11/Iceland-test.jpg) (705kb)
Post thumbnail:- [https://test.frontity.io/wp-content/uploads/2016/11/Iceland-test-1024x620.jpg](https://test.frontity.io/wp-content/uploads/2016/11/Iceland-test-1024x620.jpg) (116kb)

@luisherranz, Please share your thoughts on it.

**Comment by luisherranz** [comment]
That's handled by the browser thanks to the `srcSet` field of the `` tag.

https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Responsive_images

For that reason we are mapping all the `media_details.sizes` available and converting them to `srcSet`. Then, the browser can decide what size is needed on each device.

https://github.com/imranhsayed/frontity-twentynineteen/blob/master/packages/twentynineteen-theme/src/components/featured-media.js#L10-L21

It's still not perfect tho, as we should take into account the ratio and use only the images that match the initial ratio. If I'm not mistaken @darerodz worked on that in the old version. Is that right @darerodz? How was the implementation?

We also want to add support for WordPress media objects (with a `media_details.sizes` array) in our `<Image>` component so themes don't have to code that part over and over again.

Something like this:
```jsx
import Image from "@frontity/components/image";

// Use it manually (current behaviour)
<Image src={mySrc} srcSet={mySrcSet} sizes={mySizes} />

// or use it passing media directly
const media = state.source.attachment[id];
<Image media={media} />
```

Oh, and we need to make sure it also works with WP.com sites, where you can have any number of image sizes using a query, like `image.jpg?w=XXX`. 

If that's something you'd like to dig more into, Smit, we can explore it in more detail :)

**Comment by DAreRodz** [comment]
> It's still not perfect tho, as we should take into account the ratio and use only the images that match the initial ratio. If I'm not mistaken @DAreRodz worked on that in the old version. Is that right @DAreRodz? How was the implementation?

Yes, we were filtering those sizes in `media.sizes` that were (almost) equal to the original media and also avoiding duplicates, in order to generate the `srcSet` attribute.

```javascript
// Returns true if width/height ratio of both objects are very, very close.
// Used when computing the srcSet prop value.
const sameRatio = ({ width: w1, height: h1 }, { width: w2, height: h2 }) =>
  Math.abs(w1 / h1 - w2 / h2) < 0.01;

// Generates srcSet prop using the attachment `sizes` attribute
const srcSet = media.sizes
  .reduce((result, current) => {
    if (
      // it has the same ratio as the original and is not already in `result`
      sameRatio(current, media.original) &&
      !result.find(size => size.width === current.width)
    ) {
      result.push(current);
    }
    return result;
  }, [])
  .map(item => {
    const { pathname } = new URL(item.url);
    const url = cdn && pathname ? `${cdn}${pathname}` : item.url;
    return `${url} ${item.width}w`;
  })
  .join(', ')
```

**Comment by luisherranz** [comment]
Thanks @DAreRodz.

We should include that logic inside `<Image>` so people don't need to replicate it.

**Pull request merged**
