### PR TITLE
Fix image height issue

### PR DESCRIPTION
**Pull request by imranhsayed**
Fixes image height issue with following steps:
1. Calculate the image container width in relation to window prior to image render.
2. Get the required image height in proportion to the actual image size and the size of the container.
3. Set the container height to the required image height.

**Bug:**
window element is not found intermittently in the component.

### CODE REVIEW

**Comment by luisherranz** [comment]
I know nothing about CSS, but somehow this works in Mars without any JavaScript calculation, only CSS.

@darerodz, could you please take a look and let us know how you did it in Mars?

**Comment by luisherranz** [comment]
@darerodz 👆 ☺️

**Comment by DAreRodz** [comment]
Looking at this right now.

**Comment by imranhsayed** [comment]
> I know nothing about CSS, but somehow this works in Mars without any JavaScript calculation, only CSS.
> 
> @DAreRodz, could you please take a look and let us know how you did it in Mars?

Hi @luisherranz ,
We have checked in Mars theme, it has fixed height of `300px` for image container ( `featured-media.js` Line:38 ).
We cannot give a fixed height in twentynineteen because images can be of different sizes.
That's why we had to do the calculation.

**Comment by DAreRodz** [comment]
@imranhsayed, you are right, in `mars-theme` we are setting a fixed height of `300px`. That's how the image space is reserved.

The problem with height calculation with JS is that the container width is not possible to obtain during SSR...  🙁

**Comment by DAreRodz** [comment]
Uhm, other option could be creating an image container with a fixed aspect ratio (calculated using absolute width and height properties from the image). Maybe using some method from [this link](https://css-tricks.com/aspect-ratio-boxes/).

What do you think, guys?

**Comment by luisherranz** [comment]
> Uhm, other option could be creating an image container with a fixed aspect ratio

Would that:
1. solve the problem?
3. be a CSS-only solution?
2. work in SSR?

**Comment by luisherranz** [comment]
By the way, how does this work on the original theme? Are they allowing images to jump around like this?

**Comment by DAreRodz** [comment]
I just checked and yes, the same thing happens in the original theme.

**Comment by DAreRodz** [comment]
> > Uhm, other option could be creating an image container with a fixed aspect ratio
> 
> Would that:
> 
> 1. solve the problem?
> 2. be a CSS-only solution?
> 3. work in SSR?

Yes it would, the only thing that has to be calculated is the ratio, and that can be done during SSR using the width and height attributes from the image data.

**Comment by luisherranz** [comment]
What happens if the width and height is not available? I guess we can opt-out and leave it as it is now, right?

Does it make sense to add this behaviour to our `<Image>` component? Or is this something that need to be done on each theme?

**Comment by DAreRodz** [comment]
> What happens if the width and height is not available? I guess we can opt-out and leave it as it is now, right?

lf the width and height are not available, then a default ratio or something like that should be used, I think.

> Does it make sense to add this behaviour to our `<Image>` component? Or is this something that need to be done on each theme?

In `mars-theme` we are setting a fixed height value and using `object-fit: cover` so the image scales up to cover all the available space. Using this, ratio is not preserved and images are cropped, but this isn't necessary a bad thing.

I would add a prop to the `Image` component (something like `sameRatio`) to indicate that ratio should be preserved and use it just if needed.

**Comment by smit-patadiya** [comment]
I found a possible fix for this issue with only using CSS.

But the problem only occurs when the image is comparatively too small Eg. 400px X 300px (Image got blurred in Desktop size).

**Comment by imranhsayed** [comment]
Closing this as resolved using PR : https://github.com/imranhsayed/frontity-twentynineteen/pull/18

**Pull request closed without merging**
